#!/bin/bash

read -p "What is your name?" name
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"
echo "salut $name!"