#!/bin/bash

echo "What is your name?"
read name
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"
echo "salut $name"